### ISSUE TITLE
网上购买的crazyflie和crazyratio测试飞行总是飞歪

### ISSUE THREAD

**Issue by guozk** [NOKOV-MOCAP/nokov-vm#1]
网上购买的crazyflie和crazyratio测试飞行总是飞歪，起飞就飞歪。

**Comment by duguguang** [comment]
首次购买的飞行套件，您可以尝试手动更新固件，针对RadioPA

![图片](https://github.com/NOKOV-MOCAP/nokov-vm/assets/28754922/7f9827bd-ff24-4c49-b87b-044474da0d6d)
